/**
 * Background Configuration
 * 
 * AUTO-GENERATED by scripts/generate_backgrounds.py
 * Do not edit manually - regenerate using the script.
 */

export interface BackgroundImage {
    id: string;
    filename: string;
    tags: string[];
}

export const backgrounds: BackgroundImage[] = [
    { id: "bg1", filename: "sunny_meadow_clearing.png", tags: ["sunshine", "happy", "bright", "meadow", "flowers", "cheerful", "peaceful", "countryside", "nature", "relaxing"] },
    { id: "bg2", filename: "rainbow_field.png", tags: ["rainbow", "colorful", "sky", "joyful", "clouds", "happy", "pride", "magical", "bright", "whimsical"] },
    { id: "bg3", filename: "dark_enchanted_forest.png", tags: ["dark", "mysterious", "forest", "spooky", "night", "scary", "halloween", "gothic", "eerie", "enchanted"] },
    { id: "bg4", filename: "ocean_sunset_beach.png", tags: ["ocean", "sunset", "beach", "peaceful", "waves", "tropical", "vacation", "hawaii", "california", "chill", "relaxing", "romantic"] },
    { id: "bg5", filename: "snowy_mountain_peak.png", tags: ["snow", "mountain", "cold", "winter", "majestic", "skiing", "alps", "everest", "adventure", "climbing", "christmas"] },
    { id: "bg6", filename: "magical_castle_grounds.png", tags: ["castle", "magical", "fantasy", "fairy tale", "royal", "princess", "prince", "kingdom", "disney", "medieval", "enchanted"] },
    { id: "bg7", filename: "space_nebula.png", tags: ["space", "stars", "nebula", "cosmic", "galaxy", "astronaut", "nasa", "sci-fi", "planets", "universe", "interstellar"] },
    { id: "bg8", filename: "autumn_park_path.png", tags: ["autumn", "leaves", "park", "orange", "peaceful", "fall", "october", "cozy", "walking", "nature", "calm"] },
    { id: "bg9", filename: "underwater_coral_reef.png", tags: ["underwater", "ocean", "coral", "fish", "blue", "diving", "scuba", "marine", "nemo", "tropical", "aquarium"] },
    { id: "bg10", filename: "cherry_blossom_garden.png", tags: ["cherry", "blossom", "pink", "spring", "japan", "tokyo", "sakura", "romantic", "asian", "peaceful", "beautiful"] },
    { id: "bg11", filename: "desert_sand_dunes.png", tags: ["desert", "sand", "hot", "dry", "adventure", "sahara", "egypt", "dubai", "middle east", "camels", "exotic"] },
    { id: "bg12", filename: "city_night_skyline.png", tags: ["city", "night", "lights", "urban", "modern", "toronto", "new york", "nyc", "downtown", "skyscrapers", "metropolis", "busy"] },
    { id: "bg13", filename: "enchanted_garden.png", tags: ["garden", "enchanted", "flowers", "magical", "nature", "fairy", "whimsical", "secret", "beautiful", "peaceful"] },
    { id: "bg14", filename: "stormy_sky.png", tags: ["storm", "clouds", "dramatic", "thunder", "intense", "rain", "lightning", "dark", "moody", "powerful", "epic"] },
    { id: "bg15", filename: "cozy_cabin_interior.png", tags: ["cabin", "cozy", "warm", "home", "comfort", "fireplace", "winter", "log cabin", "rustic", "hygge", "safe"] },
    { id: "bg16", filename: "tropical_jungle.png", tags: ["jungle", "tropical", "adventure", "green", "wild", "amazon", "rainforest", "exotic", "exploring", "animals", "nature"] },
    { id: "bg17", filename: "floating_islands.png", tags: ["floating", "islands", "fantasy", "dreamy", "surreal", "avatar", "magical", "sky", "imagination", "otherworldly"] },
    { id: "bg18", filename: "northern_lights.png", tags: ["aurora", "northern lights", "night", "magical", "arctic", "iceland", "norway", "cold", "beautiful", "sky"] },
    { id: "bg19", filename: "candy_land.png", tags: ["candy", "sweet", "colorful", "fun", "whimsical", "dessert", "sugar", "playful", "kids", "happy", "bright"] },
    { id: "bg20", filename: "ancient_temple_ruins.png", tags: ["ancient", "ruins", "history", "mystery", "adventure", "temple", "archaeology", "indiana jones", "explorer", "old", "stone"] },
];

// Default fallback background if matching fails
export const defaultBackground = backgrounds[0];
